version: 0.2

env:
  variables:
    CONTAINER_REPOSITORY_URL: 946702831620.dkr.ecr.us-east-1.amazonaws.com/eb-deployment-test
    TAG_NAME: latest

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker pull $CONTAINER_REPOSITORY_URL:$TAG_NAME || true
  build:
    commands:
      - docker build --cache-from $CONTAINER_REPOSITORY_URL:$TAG_NAME --tag $CONTAINER_REPOSITORY_URL:$TAG_NAME .
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL
