version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
      - chmod +x linux-install-1.10.1.763.sh
      - ./linux-install-1.10.1.763.sh     
  build:
    commands:
      - clojure -X:uberjar
artifacts:
  files:
    - eb-deployment-test.jar
    - Procfile
    - requirements.txt
    - prepare-prod.sh
    - run-prod.sh
cache:
  paths:
    - '/root/.m2/**/*'
    - '.cpcache/**/*'
