version: 0.2

env:
  variables:
    CONTAINER_REPOSITORY_URL: 946702831620.dkr.ecr.us-east-1.amazonaws.com/eb-deployment-test
    AWS_DEFAULT_REGION: us-east-1
    TAG_NAME: latest

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $CONTAINER_REPOSITORY_URL
      - docker login -u $dockerhub_username -p $dockerhub_password
      - docker pull $CONTAINER_REPOSITORY_URL:$TAG_NAME || true
  build:
    commands:
      - docker build --cache-from $CONTAINER_REPOSITORY_URL:$TAG_NAME --tag $CONTAINER_REPOSITORY_URL:$TAG_NAME .
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL
      - printf '[{"name":"hello-eb-deployment","imageUri":"%s"}]' $CONTAINER_REPOSITORY_URL > imagedefinitions.json

artifacts:
  files:
    - Dockerrun.aws.json
    - imagedefinitions.json
